export const NUM_OF_GUESSES_ALLOWED = 6;
export const NUM_OF_CHARS = 5;
export const KEYBOARD_CHARS_UPPER_ROW = 'QWERTYUIOP';
export const KEYBOARD_CHARS_MIDDLE_ROW = 'ASDFGHJKL';
export const KEYBOARD_CHARS_LOWER_ROW = 'ZXCVBNM';
